### ISSUE TITLE
替换后无法连接到服务器，appium服务已连接

### ISSUE THREAD

**Issue by meihaoyidian** [Jodeee/fasttestDemo#1]
![image](https://user-images.githubusercontent.com/26756176/88372717-0ab55d00-cdc9-11ea-8baa-ab7fab2a024f.png)

**Comment by Jodeee** [comment]
1.请确认WDA是否安装成功
2.iOS下automationName应该配置：XCUITest
3.Appium下需要加上deviceName配置项
参考文档：http://appium.io/docs/cn/writing-running-appium/caps/
